### ISSUE TITLE
Remove usage of Boogie2SMT.constructAuxiliaryGlobalBoogieVar from RankVarConstructor

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#107]

**Comment by Heizmann** [comment]
@danieldietsch @Langenfeld done
There was some "collateral damage". We have some crafted programs that do not contain any integer variables. Ranking functions have type int. On these programs the backtranslation from SMT to Boogie fails, because it does not know the type int.
There are various workarounds for the problem. But I do not want to implement one by now and postpone the problem at least for a few days.
