### ISSUE TITLE
Ultimate throws syntax error when encountering "cexpr" attribute

### ISSUE THREAD

**Issue by liammachado** [ultimate-pa/ultimate#283]
There is an issue I've been having with Ultimate Automizer on SMACK generated .bpl files (https://github.com/smackers/smack). Ultimate is currently throwing an "incorrect syntax" error when it encounters the "cexpr" attribute. This attribute appears a couple times in every SMACK .bpl file; for example, you can see this attribute show up on lines 122 and 128 of the .bpl file I've attached.

[sample.zip](https://github.com/ultimate-pa/ultimate/files/1543751/sample.zip)

I actually have been encountering this issue since I first started working with Ultimate several months ago, but so far have been either manually removing the attribute statement, or disabling their generation within SMACK. Would there be a way for Ultimate Automizer to not throw a syntax error when running into this attribute, possibly by simply ignoring it?

**Comment by Heizmann** [comment]
The problem is that this occurs as an attribute of a call statement.
``call {:cexpr "smack:entry:main"} boogie_si_record_ref(main);``
This is not legal in Boogie. According to the [Boogie standard](https://www.microsoft.com/en-us/research/publication/this-is-boogie-2-2/) cannot have attributes.
We would have to change our Boogie parser and our Boogie AST.
This is doable. However it would be great if you could give us some additional arguments for doing that. E.g., is this extension of Boogie documented somewhere? Which other tools are using the extension? What is the semantics? (really just an attribute) What is the exact syntax, are there also other statements that should get attributes?

Usually, I dislike to support non-standard extensions since they tend to become incompatible on the long run.

**Comment by danieldietsch** [comment]
We have seen this issue with a number of other tools that generate Boogie input for us. Afaik, there is currently no real Boogie standard but rather some kind of string that is accepted by the Boogie tool. Boogie itself accepts attributes at call statements. 
Afaik there is really no semantics to it, it is just an attribute. Although many tools use it to mark the entry point(s) to their programs. 

I will try and add support for this (attributes and call statements) and then list it under extensions (as we list our changes relative to the document linked by @Heizmann  in the comment above).

**Comment by liammachado** [comment]
Sounds good, thanks!

**Comment by liammachado** [comment]
Hey, I was wondering if there's been any progress on this issue? I've been trying again to verify SMACK-generated .bpl files with Ultimate Automizer, and it is resulting in the same error when it encounters the "cexpr" attribute.

**Comment by danieldietsch** [comment]
Ah, I completely forgot about this issue. I will look into it.
