### ISSUE TITLE
Enum translation broken

### ISSUE THREAD

**Issue by jhoenicke** [ultimate-pa/ultimate#333]
Ultimate has issues with this minified example taken from the trezor-mcu codebase:
[ctrans-unsupported-syntax-enum-struct.c](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/CToBoogieTranslation/trezor/ctrans-unsupported-syntax-enum-struct.c), see #325.

C code:
```
enum rcc_clock_3v3 {
 RCC_CLOCK_3V3_120MHZ,
 RCC_CLOCK_3V3_END
};
```

Boogie Translation:
```
axiom ~rcc_clock_3v3~0~RCC_CLOCK_3V3_120MHZ == 0;
axiom ~rcc_clock_3v3~0~RCC_CLOCK_3V3_END == 0;
const ~rcc_clock_3v3~0~RCC_CLOCK_3V3_120MHZ : int;
const ~rcc_clock_3v3~0~RCC_CLOCK_3V3_END : int;
```

Expected would be 
```
axiom ~rcc_clock_3v3~0~RCC_CLOCK_3V3_END == 1;
```

**Comment by Heizmann** [comment]
To the best of my knowledge we stopped using the axioms for performance reasons and replaced enum constants by the corresponding int values already in our C translation.

Since 28 days(!) the enum testcases that we already have are failing https://monteverdi.informatik.uni-freiburg.de/ci/job/Ultimate%20Nightly/lastBuild/testReport/
Can maybe @alexandernutz or @danieldietsch say something here?
The persons who changed that probably had a reason for not introducing int values immediately.

**Comment by danieldietsch** [comment]
Its actually 37 days if you look at different settings. 

But I did not change anything regarding enums. 
Maybe @alexandernutz knows more?

**Comment by alexandernutz** [comment]
I broke them. Hopefully repaired by the above bugfix.
I don't know anything about the axiom business. As far as I can see, the solution with axioms is in place at least since May 2016.

**Comment by Heizmann** [comment]
As far as I remember, the axioms were always there. But they were useless because we did not use the corresponding constants in the translation.
I did not want to delete the code that produced the axioms because we might use them in the future.

**Comment by invd** [comment]
Recent patches have improved the enum behavior for the testcase. 

Ultimate 0.1.23-f020fd9:
```
axiom ~rcc_clock_3v3~0~RCC_CLOCK_3V3_120MHZ == 0;
axiom ~rcc_clock_3v3~0~RCC_CLOCK_3V3_END == 1;
const ~rcc_clock_3v3~0~RCC_CLOCK_3V3_120MHZ : int;
const ~rcc_clock_3v3~0~RCC_CLOCK_3V3_END : int;
```
