### ISSUE TITLE
Nontermination bug in TransitiveClosure

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#350]
`Deque<StronglyConnectedComponent<NODE>> frontier` is never emptied.

Input:svcomp/heap-manipulation/dancing_true-unreach-call_false-valid-memtrack.i 
Settings:settings/svcomp2017/automizer/svcomp-Reach-32bit-Automizer_Bitvector.epf 
Toolchain:toolchains/AutomizerC.xml

**Comment by Heizmann** [comment]
I did not had a closer look because I presume @alexandernutz is much faster.

**Comment by alexandernutz** [comment]
I'll have a look.

**Comment by alexandernutz** [comment]
The problem is:
 - Transitive closure relies on the successor relation (induced by SccComputation.getComponentsSuccessorsProvider(..), here, this is the call graph projected to strongly connected components) being acyclic.
 - For the given example this is not the case, because the Scc, that only consists of procedure 
`__U_MULTI_fC__data_sv_benchmarks_c_heap_manipulation_dancing_true_unreach_call_false_valid_memtrack_i__is_list_containing_x` has itself as a successor, it seems.

I see two possible fixes:
 - An easy fix on my end would be to not readd the Scc that is processed at the current loop iteration to the frontier. That that would not account for larger loops in the successor relation, but probably SccComputation avoids larger loops anyway.
 - I think a better fix would be to have the successor relation between Sccs be really acyclic, i.e., also not contain "self loops", i.e., to be irreflexive. -- Does someone else want to fix this perhaps?

**Comment by Heizmann** [comment]
I cannot understand the problem description.
What is "not the case"? Is the SCC computation not correct?

Maybe your are only interested in balls (SCCs with at least one edge). There is a method that returns all balls.

**Comment by alexandernutz** [comment]
Ok, I'll try to be clearer:
 - The SccComputation has the method 'SccComputation.getComponentsSuccessorsProvider(..)'
 - This method effectively returns a graph over the Sccs, let's call it G.
 - When implementing 'TransitiveClosure.computeTransitiveClosure(..)' I assumed that G is acyclic, but it is not.

Now my question is: Shouldn't this graph over the Sccs always be acyclic?

If yes:
 We should fix SccComputation (or some subclass of it)
If no:
 I can implement a simple fix for TransitiveClosure that avoids the problem if G has cycles of length at most 1.

**Comment by alexandernutz** [comment]
Let sComp instanceof SccComputation,
Let sucProv = sComp.getComponentsSuccessorsProvider(),
G := { (scc1, scc2) | exists n. scc2 = sucProv.getSuccessors(scc1).[next()]^n }

**Comment by Heizmann** [comment]
1. Then this graph should be acyclic. So there is probably a bug.
2. I would call that not "successor" but "ancestor" to indicate that it does not return direct successors.
3. It would be nice if this would be documented somewhere.

**Comment by Heizmann** [comment]
Honestly, I have to say that I doubt that the bug is in the SCC computation itself since this is used in many parts of Ultimate.
I did not implement this "getComponentsSuccessorsProvider()". So I would prefer if it could be fixed by someone else.

**Comment by alexandernutz** [comment]
Concerning 2. : There might be room for misunderstandings here: the [next()]^n iterates over the successors of a single node; this graph is not transitively closed or something like that.

Written as a set, the iterator sucProv.getSuccessors(scc1) would look like this:
Let I be the input graph of the SccComputation,
{ scc2 | exists x, y. x in scc1, y in scc2, (x,y) in I }

Thus I would favour "successor" over "ancestor" for the method name.

**Comment by alexandernutz** [comment]
Anyway: should I implement the workaround in TransitiveClosure for the time until the status of SccComputation is clear/fixed?

**Comment by alexandernutz** [comment]
oh, no, I was hoping for Daniel or so.. I'll check..
