### ISSUE TITLE
AssertionError: cannot convert to CArray

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#362]
Input:termination/termcomp2016/C/SV-COMP_Mixed_Categories/cs_fib_longer_true-unreach-call.c Settings:settings/buchiAutomizer/termcomp2017-Noproofs.epf Toolchain:toolchains/AutomizerAndBuchiAutomizerCInlineWithBlockEncoding.xml

Maybe a known conceptual problem and not a simple bug.

**Comment by alexandernutz** [comment]
First analysis of the problem: (I think it's not a conceptual problem)
 - there is a global variable
int j[7] = {1};
 - the problem occurs in this piece of code (inside some function, line 696):
 int j;
 for (j=0; j<=2; j++)
 - the problem:
  instead of the local j that should shadow the global j, the symbol table returns the global one's SymbolTableValue.
 - the suspect:
  multiparserenaming
 @danieldietsch : you are more familiar with how the symbol table should work after the multiparse-changes -- maybe you see an easy fix?

**Comment by danieldietsch** [comment]
I had a look .. its complicated. 
You are right, it is related to the multiparse renaming. We only prefix global variables and procedure names, but we miss the lookup in this case. 
I (hopefully) fixed this issue with ba12c21 but now I get another issue with struct field names. 

Perhaps @buehlery has time (although it is on very short notice) and can have a look at this problem.

**Comment by buehlery** [comment]
Seems like a corner case I forgot to cover.

The fix in ba12c21 which disables multiparse renaming should fix the problem.

Because multiparse-renamed symbols are always global (variables, functions) there should be no 'false-positive' where the first 'if' would find the wrong symbol as that would mean there would be a symbol with the same name as the renamed symbol (pre-renaming) in an outer scope.

As for the struct issue I have no idea what could cause that, but as mentioned in the edit this might happen because of something else.

**Comment by alexandernutz** [comment]
To me, this still looks like a multiparse-renaming issue.
It is looking for a struct field named "i", but the struct only has a field named "__U_MULTI_fC__data_ultimate_pa_trunk_examples_termination_termcomp_____C_SV_COMP_Mixed_Categories_cs_fib_longer_true_unreach_call_c__i".
Am I overlooking something?
