### ISSUE TITLE
AssertionError: no entry in symbol table for C-ID __ret

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#405]
Occurs e.g., in
`Input:svcomp/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_configure_pc8736x_gpio_set_true-unreach-call.i`
with any toolchain/settings.

Occurs probably in all examples where we had a few days ago the following error message.
`UnsupportedOperationException: Cannot understand initializer with more than two children. Is this a struct initialization?`

**Comment by alexandernutz** [comment]
The problem here was the following a statement of the form 
 ```return ({int x; x});```
This compound statement with a declaration inside confused the symbol table lookup.

A fix in the context of return statements is 
sha 1c8ab049dc6cbe59ce0e4babea1aa319c854289e
a corresponding regression test is
sha 69cedd259d402476a46a0696423918bb91510d69

However, the symbol table lookup probably needs to be solved more generally here. This should happen during our coming rework of the symbol table.
