### ISSUE TITLE
Web interface does not show all results

### ISSUE THREAD

**Issue by Heizmann** [ultimate-pa/ultimate#425]
The web interface of Automizer does not show any result for the attached program.
[modBug.txt](https://github.com/ultimate-pa/ultimate/files/3318038/modBug.txt)
In the GUI everything works fine.
If you replace the modulo operation by a different operation you also get a result in the web interface.

**Comment by danieldietsch** [comment]
A quick investigation shows that the webinterface's ``tool.js`` has a function
````
function decode_utf8(s)
{
  return decodeURIComponent(unescape(s));
}
````
This function receives the short and long description of results that were passed to -- ultimatively -- ``addResults`` in ``tools.js``. 

It fails because ``%23`` is actually ``#`` after ``unescape``, and ``#`` is forbidden as input for  ``decodeURIComponent``.

Everything about this seems rather fishy. 
* ``unescape`` is deprecated since JS 1.5
* a replacement is either ``decodeURI`` or ``decodeURIComponent``
* who encodes the result tests with what method and why?

**Comment by Heizmann** [comment]
If no important example is affected, its fine for me if we postpone this.
I just wanted to use the issue to save this example and report that this might be the reason for other problems.
