### ISSUE TITLE
RESULT: Ultimate could not prove your program: Toolchain returned no result.

### ISSUE THREAD

**Issue by IridescentL** [ultimate-pa/ultimate#498]
I use the nightly build UReqCheck file and run run_complete_analysis.py script file with -ar option to analyze a .req file, everything seems fine, but the log file prints some unexpected results. Here are the log and .req screenshots. My environment is CENTOS 7.
![image](https://user-images.githubusercontent.com/24289271/92426239-021fb700-f1bc-11ea-9105-6d536b828d2b.png)
![image](https://user-images.githubusercontent.com/24289271/92426256-09df5b80-f1bc-11ea-8ff3-c8ffa73e653b.png)
Is it normal to print this or something wrong happens?

**Comment by danieldietsch** [comment]
No, this is the actual result. The message at the end (``Ultimate could not prove your program``) is just because Ultimate is usually a program verfier and we did not bother (yet) to add the requirement result types to the overall result evaluation mechanism. 

So, congratulations, your requirements set has no errors that we would find ;)

**Comment by danieldietsch** [comment]
If this answers your question, please close the issue.

**Comment by IridescentL** [comment]
Thanks!
