### ISSUE TITLE
Better format for rt-inconsistency counterexamples

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#525]
The current format is rather hard to read, as it does only talk about offsets and is itself offset by one relative to the initial state. 
We want to have something more like this:
```
INITIAL      x=*, y=*, ....
[0;100]       x=5, y=true
[100;150]   x=5, y=false
...
```

**Comment by alopez-developair** [comment]
@danieldietsch I'm not sure if I should open a new issue for this since it's minor and related to this one, but we realized that now non-integer numbers in the intervals are represented as fractions rather than as decimals, such as `[0;197/2]`  instead of `[0;98.5]`; this makes the examples harder to read when this happens. It is a minor issue but I think we would much prefer to have the decimal representation.
