### ISSUE TITLE
Vacuities are not reported when defining value ranges that are strictly less restrictive than others (ReqCheck)

### ISSUE THREAD

**Issue by alopez-developair** [ultimate-pa/ultimate#527]
It appears that redundant variable range limitations are not reported as vacuities.

Example:

```
input A is int
input B is int

R1: Globally, it is always the case that "A>B" holds.
R2: Globally, it is always the case that "A>B+3" holds.
```

Expected: R1 should be vacuous because R2 is more restrictive. Got: No vacuity.
The reasoning is that if R2 is satisfied, then R1 is trivially satisfied.

A simplified version of the same concept:

```
input A is int

R1: Globally, it is always the case that "A>3" holds.
R2: Globally, it is always the case that "A>4" holds.
```

**Comment by henkele** [comment]
> It appears that redundant variable range limitations are not reported as vacuities.

This result is correct relative to the definition of vacuity that we use (e.g., invariants can never be vacuous). 

However, for both examples, our new redundancy analysis reports that requirement R1 is redundant. The reason is, as mentioned above, that in both cases R2 is more restrictive than R1, and R1 could be removed from the requirements set without changing its original behaviour.
