### ISSUE TITLE
ResultNotifier messages are not consistent with actual result messages

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#6]
As seen in Jan Hättig's presentation today, the result notifier states that there is no result when the real result is actually safe. Either remove the result notifier or fix this contradiction.

**Comment by Heizmann** [comment]
It seems that not all toolchains are affected. E.g., if I use the Automizer toolchain, I obtain the following.
``2015-10-28 01:47:44,575 INFO  [ResultNotifier.java:137]: RESULT: Ultimate proved your program to be correct!``
However, I agree that the ResultNotifier has to be revised some day. (Problems? E.g., how do we summarize several positive results?)

**Comment by schillic** [comment]
When using the command line interface (tested with the binary release 0.1.19) and using the AutomataScriptInterpreter (may also occur with other toolchains; not tested) on an automata file (_*.ats_) that contains an assertion (`assert(...)`), upon (successful) termination Ultimate adds the following result output: `Ultimate could not prove your program: Assertion holds`

**Comment by danieldietsch** [comment]
What is the expected behavior? 
 * No message
 * A message saying something like "Ultimate proved your program to be correct" 
 * Something automata-specific, like "Ultimate proved your automata to be correct" 

Do you have a sample input file, settings file, toolchain file (just something from our repo is enough, you do not need to attach it).

**Comment by schillic** [comment]
I do not know the expected behavior because I do not know the spec of the CLI.
It looks like "No message" would be fine because there is already a line with the (correct) result.

To reproduce, run the CLI with the toolchain [AutomataScriptInterpreter.xml](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/toolchains/AutomataScriptInterpreter.xml) and [this example](https://github.com/ultimate-pa/ultimate/blob/dev/trunk/examples/Automata/regression/nwa/operations/minimization/nwa/MinimizeSevpa_Bug05.ats), but I expect any example with assertions should do.
