### ISSUE TITLE
Fix examples\CToBoogieTranslation\Stackoverflow.c

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#61]

**Comment by alexandernutz** [comment]
The problem is:
 - We have a pointer inside a union, and the pointed-to type is that of the union.
 - We do not unify our CType objects. 
 - Two CPointer instances are equal if the pointed-to type is the same
 - Two CUnion instances are equal if the field types are the same
Here the equals call of the two pointers objects does not terminate.

I am still evaluating which solution is best here.

**Comment by alexandernutz** [comment]
Solved some time ago by the introduction of TypeHandler.areMatchingTypes(), and using it instead of CType.equals() for comparison of two CTypes.
