### ISSUE TITLE
Fix examples\CToBoogieTranslation\unnamedFieldInStruct.c

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/ultimate#69]

**Comment by alexandernutz** [comment]
contains a struct of the form
struct s {
 int ;
 char ;
}
i.e. with unnamed non-struct-or-union fields.
C11 does not allow this.
The original benchmark file should be fixed rather than Ultimate
ldv-linux-4.2-rc1\linux-4.2-rc1.tar.xz-43_2a-drivers--block--DAC960.ko-entry_point_true-unreach-call.cil.out.c

**Comment by danieldietsch** [comment]
I will recheck with the current SVCOMP set and come back to this. If this bug is still present, can @alexandernutz resolve with SVCOMP?

**Comment by enkejill** [comment]
C11 Standard 6.7.2.1 (8): "If the struct-declaration-list does not contain any
named members, either directly or via an anonymous structure or anonymous union, the
behavior is undefined."

=> The example is undefined in C11

**Comment by alexandernutz** [comment]
Cool, thanks for looking this up!
Could you perhaps commit a test file (or more than one) that makes correct use of anonymous struct/union fields instead?

example:
struct s {
  int i;
  char ;
}

I would guess the original one would work as soon as one of the fields is named, right?

Also, the case that is mentioned in your quote with something like this might be worth tracking:
struct s {
  struct {
    int i;
  };
  char ;
}

Or do we already have a test for this?
